apiVersion: v1
kind: Service
metadata:
  name: {{ include "mcp.fullname" . }}
  labels:
    {{- include "mcp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.mcp.port }}
      targetPort: mcp
      protocol: TCP
      name: mcp
  selector:
    {{- include "mcp.selectorLabels" . | nindent 4 }}
