apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent.fullname" . }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.mcp.port }}
      targetPort: mcp
      protocol: TCP
      name: mcp
    - port: {{ .Values.a2a.port }}
      targetPort: a2a
      protocol: TCP
      name: a2a
    - port: {{ .Values.fastapi.port }}
      targetPort: fastapi
      protocol: TCP
      name: fastapi
  selector:
    {{- include "agent.selectorLabels" . | nindent 4 }}
