#!/bin/sh

echo "> Parsing Terraform outputs"
DYNAMODB_WEATHER_AGENT_STATE_TABLE_NAME=$(terraform output weather_agent_table_name)

echo "DYNAMODB_WEATHER_AGENT_STATE_TABLE_NAME=$DYNAMODB_WEATHER_AGENT_STATE_TABLE_NAME"

WEATHER_DST_FILE_NAME=${WEATHER_DST_FILE_NAME:-../../../weather/.env}
echo "> Injecting values into $WEATHER_DST_FILE_NAME"
echo "" >> $WEATHER_DST_FILE_NAME
echo "DYNAMODB_WEATHER_AGENT_STATE_TABLE_NAME=$DYNAMODB_WEATHER_AGENT_STATE_TABLE_NAME" >> $WEATHER_DST_FILE_NAME

echo "> Done"
